package sh.toxic.camel;

import java_cup.runtime.*;

parser code {:
    public String errsin="";
    public void syntax_error(Symbol x){
        errsin+="\nError Sintaxis en pos Linea=" + (x.left+1) + ", Caracter=" + (x.right+1) + ", Value=" + x.value;
        throw new UnsupportedOperationException (errsin);
    }
:};

terminal num,id,str,pi,pd,ol,or,op,programa,para,hasta,paso,finpara,si,entonces,sino,finsi,mientras,hacer,finmientras,finprograma,leer,entero,tipo,escribir,asig,pc,cm;
non terminal E,T,EL,EA,Z,K,I,S,IS;

IS ::= programa S finprograma;
IS ::= programa id S finprograma;
S ::= I;
S ::= I S;
I ::= si pi EL pd entonces S finsi;
I ::= si pi EL pd entonces S sino S finsi;
I ::= para id asig T hasta id S finpara;
I ::= para id asig T hasta id paso num S finpara;
I ::= mientras pi EL pd hacer S finmientras;
I ::= id asig EL pc;
I ::= tipo Z pc;
I ::= leer Z pc;
I ::= entero Z pc;
I ::= escribir K pc;
K ::= K cm id;
K ::= K cm str;
K ::= id;
K ::= str;
Z ::= Z cm id;
Z ::= id;
EL ::= EL ol EA;
EL ::= EA;
EA ::= E or E;
EA ::= E;
E ::= E op T;
E ::= T;
T ::= num | id;
T ::= pi EL pd;

