
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package sh.toxic.camel;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int hacer = 10;
  public static final int id = 3;
  public static final int or = 7;
  public static final int EOF = 0;
  public static final int pi = 4;
  public static final int num = 2;
  public static final int op = 8;
  public static final int finmientras = 11;
  public static final int list = 15;
  public static final int mientras = 9;
  public static final int asig = 12;
  public static final int error = 1;
  public static final int ol = 6;
  public static final int pd = 5;
  public static final int pc = 13;
  public static final int tipo = 14;
  public static final int cm = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "num",
  "id",
  "pi",
  "pd",
  "ol",
  "or",
  "op",
  "mientras",
  "hacer",
  "finmientras",
  "asig",
  "pc",
  "tipo",
  "list",
  "cm"
  };
}

